# Generated by Django 3.1.4 on 2022-06-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0004_auto_20220604_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
