# Generated by Django 3.1.4 on 2022-06-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0005_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
