# Generated by Django 3.1.4 on 2022-06-23 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0006_auto_20220624_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='execrpt',
            new_name='text',
        ),
        migrations.AddField(
            model_name='posts',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
